### ISSUE TITLE
安装上真机(Android8.0)运行报错

### ISSUE THREAD

**Issue by MrHuangDaXian** [T-chuangxin/AudioWaveShow#1]
报错为Visualizer initCheck failed初始化失败,具体如下: 

Process: com.example.huang.mylayoutgroup, PID: 23660
                                                                                 java.lang.RuntimeException: Unable to resume activity {com.example.huang.mylayoutgroup/com.example.huang.mylayoutgroup.WaveformActivicy}: java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
                                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3749)
                                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3789)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2975)
                                                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:108)
                                                                                     at android.os.Looper.loop(Looper.java:206)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6733)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
                                                                                  Caused by: java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
                                                                                     at android.media.audiofx.Visualizer.<init>(Visualizer.java:218)
                                                                                     at com.example.huang.mylayoutgroup.widget.VisualizerView.link(VisualizerView.java:87)
                                                                                     at com.example.huang.mylayoutgroup.WaveformActivicy.init(WaveformActivicy.java:65)
                                                                                     at com.example.huang.mylayoutgroup.WaveformActivicy.onResume(WaveformActivicy.java:39)
                                                                                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)

**Comment by xuzhiyong017** [comment]
我也是报这个错误，有解决了吗
